---
- name: ping module demo
  hosts: all

  collections:
    - paloaltonetworks.panos

  tasks:
  - name: Get the system info
    paloaltonetworks.panos.panos_software:
      provider: '{{ provider }}'
      cmd: 'show system info'
    register: res

  - debug:
      msg: '{{ res.stdout }}'
