---
- name: ping module demo
  hosts: all
  gather_facts: yes 
  tasks:
    - name: print facts
      debug:
        msg: "IPv4 address: {{ ansible_default_ipv4.address }}"
        
    - name: Ping connection
      ansible.builtin.ping:
...
