- name: List Installed Packages on Windows
  hosts: all
  ignore_errors: true
  gather_facts: yes

  collections:
    - ansible.windows.win_service_info

  tasks:

    - name: Get info for all installed services
      ansible.windows.win_service_info:
      register: service_info

    - name: Get info for a single service
      ansible.windows.win_service_info:
        name: WinRM
      register: service_info

    - name: Get info for a service using its display name
      ansible.windows.win_service_info:
        name: Windows Remote Management (WS-Management)

    - name: Find all services that start with 'win'
      ansible.windows.win_service_info:
        name: win*
 
