---
- name: List Installed Packages on Windows
  hosts: all
  gather_facts: yes

  collections:
    - ansible.windows.win_package
    - geerlingguy.win_package_facts
    
  tasks:
    - name: Gather installed package facts
      win_package_facts:
        gather_subset: 'installed'
      register: installed_packages

    - name: Display installed packages
      debug:
        var: installed_packages.ansible_facts.packages

    - name: Generate HTML report
      template:
        src: installed_packages_report.html.j2
        dest: installed_packages_report.html
