---
- name: List Installed Packages on Windows
  hosts: all
  gather_facts: yes

  collections:
    - ansible.windows.win_package

  tasks:
    - name: Verify python installed
      win_shell: python --version
      register: result

    - debug:
        msg: "{{ result.stdout }}"

    - name: Find python binary
      win_shell: (get-command python).Source
      register: result

    - debug:
        msg: "{{ result.stdout }}"

    - name: Set where python interpreter is
      set_fact:
        ansible_python_interpretor: "{{ result.stdout_lines[0] }}"
      
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Check whether a package called foobar is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['foobar'] | length }} versions of foobar are installed!"
      when: "'foobar' in ansible_facts.packages"
    
