---
- name: List Installed Packages on Windows
  hosts: all
  gather_facts: yes


  collections:
    - ansible.windows.win_package
  tasks:

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages
